### ISSUE TITLE
plots

### ISSUE THREAD

**Issue by IlariaPalmi** [quadbiolab/scRNAseq_analysis_vignette#1]
Dear all,
I am running Seurat in a R environment  created in conda. I am following Seurat tutorial to analyse my data
>library(Seurat)
>library(dplyr)
>library(patchwork)
>library(ggplot2)

After reading the data, and creating Seurat object, I am doing some QC.
When I run
>plot=VlnPlot(Mydata, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
>plot

I do not get any Figure window or any plot. Is there a package I am missing to install?
Thanks for your help.

**Comment by zhisonghe** [comment]
Hi! Sorry for replying late. Have you solved the problem?

If not, this problem looks like a generic display problem. Are you using a remote server or your own computer? Particularly if it is the former one, you would have to make sure that the X11 forwarding is working properly. Alternatively, you can consider to output the plot to image files directly via using `png()` or `pdf()`, for instance.
