### ISSUE TITLE
data upload

### ISSUE THREAD

**Issue by ncedi12** [quadbiolab/scRNAseq_analysis_vignette#2]
Thank you for what appears to be an excellent introductory tutorial, however could you assist in including instructions on how to actually access the DS1 and DS2 practice data you use. You begin by making a Seurat object of data but no instruction on how you uploaded the data;

**Comment by zhisonghe** [comment]
Hi! Both the DS1 and DS2 data, as well as the other example data sets used in the tutorial, are available in this repository in the `data` folder. The three files per data set "barcodes.tsv.gz", "features.tsv.gz" and "matrix.mtx.gz" should be sufficient to create the Seurat object following the steps in the tutorial.
